export { PermissionsManager } from './manager'
export { checkRules, evaluateRules } from './rules'
export type { ShellPermissionRule } from './shellRuleMatching'
export { matchWildcardPattern, findMatchingRule, parsePermissionRule } from './shellRuleMatching'
export { permissionRuleValueFromString, permissionRuleValueToString, escapeRuleContent } from './permissionRuleParser'
export { createDenialTrackingState, recordDenial, recordSuccess, shouldFallbackToPrompting } from './denialTracking'
export { isPermissionExplainerEnabled, generatePermissionExplanation } from './permissionExplainer'
export { isAutoModeActive, setAutoModeActive, setAutoModeFlagCli } from './autoModeState'
export { classifyYoloAction, resetYoloState } from './yoloClassifier'
export type { PermissionUpdate } from './PermissionUpdate'
